### ISSUE TITLE
Upgrade server to PHP 7

### ISSUE THREAD

**Issue by quagliero** [quagliero/fantasee-app#13]
Everyone hates PHP but version 7 is provocative, it gets the people going!

- [x] Upgrade homestead environment
- [x] Upgrade server droplet
- [x] Remove PHP5.6 from Travis

**Comment by terrawheat** [comment]
http://askubuntu.com/questions/705880/how-to-install-php-7 perhaps?

**Comment by quagliero** [comment]
Or https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04, since it's a DO droplet running 14.04 (I think...)

**Comment by terrawheat** [comment]
If its DO... maybe just reprovision it with PHP7... its not like the data is live or anything :D

**Comment by quagliero** [comment]
Great shout. We'll nuke it.
